Feature/generic response
target-ready-2023/EventManagement-api pull request #17
Opened 2023-07-29 13:46 UTC by SakshiThawal

Added a generic response format showing the data, status code, status message, error, and metadata for GET, and DELETE API.

2023-07-29 15:45 UTC, haziq-k requested changes

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/payloads/ApiResponse.java
> +    private int statusCode;
Is this httpStatus code? if so it is not needed in the request body. It will be anyway passed as response header.
StatusMessage is also not needed, if you need you can have a field named as message.

Let us make it very simple.  We can just have below fields in the response 

```
{
  T datat;
  String error;
}
```

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/payloads/ApiResponse.java
> +@Setter
You can use @Data instead of getter and setter

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +            Object responseData = eventService.listall();
Please change Object to List<Events>

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +            ApiResponse<Object> response = new ApiResponse<>();
Create a constructor that takes data and other required fields as argument and use that

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +            ApiError error = new ApiError();
I think it is not a good idea to handle the exceptions this way. 
It is better to have a custom exception class like below and use Spring ControllerAdvice to handle that. 

```
NewExceptionClass extends RuntimeException {
   HttpStatusCode statusCode;
   String errorMessage;
   //Add more fields if required
}
```

And you can throw this exception class when ever you catch an exception that hinders the flow.
Like if you are querying DB and caught an exception. You can catch that exception and convert it into this new exception.

And in the controllerAdvice you will catch this exception and return a responseEntity object like below

 ```
handleNewException(NewExceptionClass ex) {
     //Create APIResponse and APIError class using the ex.getErrorMessage.
     return new ResponseEntity<>(ex.getStatusCode, ApiResponse)
}
```

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +            Object responseData = eventService.get(id);
Refer previous review comments

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventUserController.java
> +    public ResponseEntity<String> registerParticipant(@PathVariable Long eventId, @RequestBody Users participant) {
Why is the entire User required? You need only the userId right?

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventUserController.java
>              return ResponseEntity.status(HttpStatus.CREATED).body("Participant registered successfully.");
Use the new response structure here as well

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventUserController.java
>              return ResponseEntity.ok("Participant deregistered successfully.");
Use the new response structure here as well

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/UserController.java
> +            Object responseData = userService.listAall();
Refer previous comments

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/service/EventService.java
> +        return false;
Why false is returned here?

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/service/UserService.java
> +        return true;
Why do you have to return true here?
If the method doesn't throw any exception, that means the delete was success

2023-07-29 15:45 UTC, haziq-k commented on event-management-system/target/classes/application.properties
> +spring.jpa.hibernate.ddl-auto=update
It is not recommended to "spring.jpa.hibernate.ddl-auto", Please remove this

2023-07-29 15:51 UTC, SakshiThawal commented on event-management-system/src/main/java/com/target/eventmanagementsystem/payloads/ApiResponse.java
> +    private int statusCode;
Okay, sir, I will make changes. Do we need metadata too?

2023-07-29 16:05 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/payloads/ApiResponse.java
> +    private int statusCode;
For now, let us keep it simple, no need for metadata. If it is needed by the UI we can add it

2023-07-31 04:50 UTC, haziq-k requested changes
Let us not have the service class return ApiResponse class, the service class should return Event, User eg... objects.

2023-07-31 04:50 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +    @PostMapping("/")
this can be just `@PostMapping()` , no need for the extra `"/"`

2023-07-31 04:50 UTC, haziq-k commented on event-management-system/src/main/java/com/target/eventmanagementsystem/controller/EventController.java
> +        ApiResponse<Event> response = eventService.createEvent(event);
The service class shouldn't return `ApiResponse` object. Service class will return `Event` object and controller will convert it to `ApiResponse` object

2023-08-03 14:14 UTC, merged