Feature/tests
target-ready-2023/EventManagement-api pull request #28
Opened 2023-08-07 06:27 UTC by Vishakha-ks

Added unit tests to cover the EventController APIs, EventRegistrationController APIs and UserController APIs.

2023-08-08 07:39 UTC, haziq-k commented on src/main/main.iml
> +<?xml version="1.0" encoding="UTF-8"?>
What is the purpose of this file?

2023-08-08 07:39 UTC, haziq-k commented on src/test/test.iml
> +<?xml version="1.0" encoding="UTF-8"?>
is this file needed?

2023-08-09 12:35 UTC, Vishakha-ks commented on src/test/test.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Added to .gitignore ,both the above files, test.iml and main.iml since it's local to every system.

2023-08-09 17:02 UTC, haziq-k approved these changes
Looks good

2023-08-14 05:34 UTC, haziq-k approved these changes

2023-08-16 12:06 UTC, haziq-k requested changes
The conflicts were not resolved properly. Please remove the latest commit and resolve the conflicts properly

2023-08-17 08:53 UTC, haziq-k approved these changes

2023-08-17 09:53 UTC, merged